# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e333d36f7ef085f213baf9536a6959b072d5e7ec9714376352d00bde18360f9637b2d2dcbf8f9b5f01a89da22c579814f1cf825d07b6771461b38f3320c0e433

test:
  secret_key_base: 7f94aa01e6b566fed29541e0074fba40ce08ab5fd5d6171941fd3891b739da6c3801b537ab00fe105a6a28dcbb20361ec8bb1df5138eb0744320c0ccc8997f52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
